[package]
name = "hermes_ffi_py"
version = "0.1.0"
edition = "2024"

[dependencies]
hermes_ffi_core = { version = "0.1.0", path = "../hermes_ffi_core" }
hermes_replay_sql = { version = "0.1.0", path = "../hermes_replay_sql" }
pyo3 = { version = "0.29.0", features = ["extension-module"] }
sha3 = "0.12.0"

[features]
test-clock = []

[lib]
crate-type = ["cdylib"]
