[package]
name = "hermes_crypto_wasm-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.hermes_crypto_wasm]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "decrypt_fuzzer"
path = "fuzz_targets/decrypt_fuzzer.rs"
test = false
doc = false
